<footer class="footer-WW navbar-inverse">
            <div class="container text-center">
                <h5>&copy;2017-2018 Andrew Haaland, All rights reserved.</h5>
                <div class="footAlign">
                    Proudly Powered By:
                    <a href="https://www.wunderground.com/weather/api/"><img src = /Images/wunderlogo.png alt = "Weather Underground" style ="height: 30px;"></a>
                </div>
          </div>
</footer>
