        <nav class="navbar navbar-inverse navbar-static-top nav-no-space">
        <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.php">WeatherWonder <span class="glyphicon glyphicon-cloud"></span> </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li ><a href="index.php">Home</a></li>
           <!-- <li><a href="historicalDump.php">History Dump</a></li>-->
          </ul>
          <!--<div class="navbar-right">
              <p class="navbar-text ">Hello, Guest!</p>
               <Button id = "logBTN" type="submit" class="btn btn-primary navbar-btn pull-left" data-toggle="modal" data-target="#loginModal" role="login">Sign In</Button> 
                <p class="navbar-text">or <a href="signup.php">Sign up today!</a></p>
          </div>-->
          </div>
        </div>
        </nav>